// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gradFun4delta
NumericVector gradFun4delta(NumericMatrix u, NumericVector theta, NumericVector delta);
RcppExport SEXP dng_gradFun4delta(SEXP uSEXP, SEXP thetaSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(gradFun4delta(u, theta, delta));
    return rcpp_result_gen;
END_RCPP
}
// gradFun4df
NumericVector gradFun4df(int i, NumericMatrix rho, NumericVector df, NumericMatrix u_quantile);
RcppExport SEXP dng_gradFun4df(SEXP iSEXP, SEXP rhoSEXP, SEXP dfSEXP, SEXP u_quantileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u_quantile(u_quantileSEXP);
    rcpp_result_gen = Rcpp::wrap(gradFun4df(i, rho, df, u_quantile));
    return rcpp_result_gen;
END_RCPP
}
// gradFun4theta
NumericVector gradFun4theta(NumericMatrix u, NumericVector theta, NumericVector delta);
RcppExport SEXP dng_gradFun4theta(SEXP uSEXP, SEXP thetaSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(gradFun4theta(u, theta, delta));
    return rcpp_result_gen;
END_RCPP
}
// dCpl
NumericVector dCpl(std::string CplNM, NumericMatrix u, List parCpl, bool log0);
RcppExport SEXP dng_dCpl(SEXP CplNMSEXP, SEXP uSEXP, SEXP parCplSEXP, SEXP log0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type CplNM(CplNMSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< List >::type parCpl(parCplSEXP);
    Rcpp::traits::input_parameter< bool >::type log0(log0SEXP);
    rcpp_result_gen = Rcpp::wrap(dCpl(CplNM, u, parCpl, log0));
    return rcpp_result_gen;
END_RCPP
}
// dmvNormVecFun
NumericVector dmvNormVecFun(int i, NumericVector x, NumericVector rho);
RcppExport SEXP dng_dmvNormVecFun(SEXP iSEXP, SEXP xSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvNormVecFun(i, x, rho));
    return rcpp_result_gen;
END_RCPP
}
// dsplitt
NumericVector dsplitt(NumericVector x, NumericVector mu, NumericVector df, NumericVector phi, NumericVector lmd, bool logarithm);
RcppExport SEXP dng_dsplitt(SEXP xSEXP, SEXP muSEXP, SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP, SEXP logarithmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    Rcpp::traits::input_parameter< bool >::type logarithm(logarithmSEXP);
    rcpp_result_gen = Rcpp::wrap(dsplitt(x, mu, df, phi, lmd, logarithm));
    return rcpp_result_gen;
END_RCPP
}
// FUN
NumericMatrix FUN(int i, NumericMatrix x, NumericVector mu, NumericVector df, NumericMatrix rho, NumericVector uIdx);
RcppExport SEXP dng_FUN(SEXP iSEXP, SEXP xSEXP, SEXP muSEXP, SEXP dfSEXP, SEXP rhoSEXP, SEXP uIdxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type uIdx(uIdxSEXP);
    rcpp_result_gen = Rcpp::wrap(FUN(i, x, mu, df, rho, uIdx));
    return rcpp_result_gen;
END_RCPP
}
// ghypergeo
NumericVector ghypergeo(NumericMatrix a, NumericMatrix b, NumericVector z, int k);
RcppExport SEXP dng_ghypergeo(SEXP aSEXP, SEXP bSEXP, SEXP zSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(ghypergeo(a, b, z, k));
    return rcpp_result_gen;
END_RCPP
}
// ibeta
double ibeta(double x, double a, double b, bool log0, bool reg);
RcppExport SEXP dng_ibeta(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP, SEXP log0SEXP, SEXP regSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type log0(log0SEXP);
    Rcpp::traits::input_parameter< bool >::type reg(regSEXP);
    rcpp_result_gen = Rcpp::wrap(ibeta(x, a, b, log0, reg));
    return rcpp_result_gen;
END_RCPP
}
// splitt_kurtosis
NumericVector splitt_kurtosis(NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_splitt_kurtosis(SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(splitt_kurtosis(df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// logCplGrad
List logCplGrad(std::string CplNM, NumericMatrix u, List parCpl, std::string parCaller);
RcppExport SEXP dng_logCplGrad(SEXP CplNMSEXP, SEXP uSEXP, SEXP parCplSEXP, SEXP parCallerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type CplNM(CplNMSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< List >::type parCpl(parCplSEXP);
    Rcpp::traits::input_parameter< std::string >::type parCaller(parCallerSEXP);
    rcpp_result_gen = Rcpp::wrap(logCplGrad(CplNM, u, parCpl, parCaller));
    return rcpp_result_gen;
END_RCPP
}
// logDensFun
NumericVector logDensFun(NumericMatrix u, NumericVector theta, NumericVector delta);
RcppExport SEXP dng_logDensFun(SEXP uSEXP, SEXP thetaSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(logDensFun(u, theta, delta));
    return rcpp_result_gen;
END_RCPP
}
// MargiModelGrad
List MargiModelGrad(NumericVector y, List par, std::string type, std::string parCaller, GenericVector denscaller);
RcppExport SEXP dng_MargiModelGrad(SEXP ySEXP, SEXP parSEXP, SEXP typeSEXP, SEXP parCallerSEXP, SEXP denscallerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< List >::type par(parSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type parCaller(parCallerSEXP);
    Rcpp::traits::input_parameter< GenericVector >::type denscaller(denscallerSEXP);
    rcpp_result_gen = Rcpp::wrap(MargiModelGrad(y, par, type, parCaller, denscaller));
    return rcpp_result_gen;
END_RCPP
}
// splitt_mean
NumericVector splitt_mean(NumericVector mu, NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_splitt_mean(SEXP muSEXP, SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(splitt_mean(mu, df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// pochhammer
NumericMatrix pochhammer(NumericVector a, IntegerVector n, bool log0);
RcppExport SEXP dng_pochhammer(SEXP aSEXP, SEXP nSEXP, SEXP log0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type log0(log0SEXP);
    rcpp_result_gen = Rcpp::wrap(pochhammer(a, n, log0));
    return rcpp_result_gen;
END_RCPP
}
// psplitt
NumericVector psplitt(NumericVector q, NumericVector mu, NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_psplitt(SEXP qSEXP, SEXP muSEXP, SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(psplitt(q, mu, df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// qsplitt
NumericVector qsplitt(NumericVector p, NumericVector mu, NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_qsplitt(SEXP pSEXP, SEXP muSEXP, SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(qsplitt(p, mu, df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// rsplitt
NumericVector rsplitt(int n, NumericVector mu, NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_rsplitt(SEXP nSEXP, SEXP muSEXP, SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(rsplitt(n, mu, df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// splitt_skewness
NumericVector splitt_skewness(NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_splitt_skewness(SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(splitt_skewness(df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// splitt_var
NumericVector splitt_var(NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_splitt_var(SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(splitt_var(df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
