# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradFun4delta <- function(u, theta, delta) {
    .Call('dng_gradFun4delta', PACKAGE = 'dng', u, theta, delta)
}

gradFun4df <- function(i, rho, df, u_quantile) {
    .Call('dng_gradFun4df', PACKAGE = 'dng', i, rho, df, u_quantile)
}

gradFun4theta <- function(u, theta, delta) {
    .Call('dng_gradFun4theta', PACKAGE = 'dng', u, theta, delta)
}

dCpl <- function(CplNM, u, parCpl, log0) {
    .Call('dng_dCpl', PACKAGE = 'dng', CplNM, u, parCpl, log0)
}

dmvNormVecFun <- function(i, x, rho) {
    .Call('dng_dmvNormVecFun', PACKAGE = 'dng', i, x, rho)
}

dsplitt <- function(x, mu, df, phi, lmd, log0) {
    .Call('dng_dsplitt', PACKAGE = 'dng', x, mu, df, phi, lmd, log0)
}

FUN <- function(i, x, mu, df, rho, uIdx) {
    .Call('dng_FUN', PACKAGE = 'dng', i, x, mu, df, rho, uIdx)
}

ghypergeo <- function(a, b, z, k) {
    .Call('dng_ghypergeo', PACKAGE = 'dng', a, b, z, k)
}

ibeta <- function(x, a, b, log0, reg) {
    .Call('dng_ibeta', PACKAGE = 'dng', x, a, b, log0, reg)
}

splitt_kurtosis <- function(df, phi, lmd) {
    .Call('dng_splitt_kurtosis', PACKAGE = 'dng', df, phi, lmd)
}

logCplGrad <- function(CplNM, u, parCpl, parCaller) {
    .Call('dng_logCplGrad', PACKAGE = 'dng', CplNM, u, parCpl, parCaller)
}

logDensFun <- function(u, theta, delta) {
    .Call('dng_logDensFun', PACKAGE = 'dng', u, theta, delta)
}

MargiModelGrad <- function(y, par, type, parCaller, denscaller) {
    .Call('dng_MargiModelGrad', PACKAGE = 'dng', y, par, type, parCaller, denscaller)
}

splitt_mean <- function(mu, df, phi, lmd) {
    .Call('dng_splitt_mean', PACKAGE = 'dng', mu, df, phi, lmd)
}

pochhammer <- function(a, n, log0) {
    .Call('dng_pochhammer', PACKAGE = 'dng', a, n, log0)
}

psplitt <- function(q, mu, df, phi, lmd) {
    .Call('dng_psplitt', PACKAGE = 'dng', q, mu, df, phi, lmd)
}

qsplitt <- function(p, mu, df, phi, lmd) {
    .Call('dng_qsplitt', PACKAGE = 'dng', p, mu, df, phi, lmd)
}

rsplitt <- function(n, mu, df, phi, lmd) {
    .Call('dng_rsplitt', PACKAGE = 'dng', n, mu, df, phi, lmd)
}

splitt_skewness <- function(df, phi, lmd) {
    .Call('dng_splitt_skewness', PACKAGE = 'dng', df, phi, lmd)
}

splitt_var <- function(df, phi, lmd) {
    .Call('dng_splitt_var', PACKAGE = 'dng', df, phi, lmd)
}

